### ISSUE TITLE
is there a way to make a html version?

### ISSUE THREAD

**Issue by loniop** [pahaze/Mistful-Crimson-Morning#3]
### What is your question?

im not that good with fnf engines and im most likely missing something,

**Comment by pahaze** [comment]
Sadly no as the stages are not hardcoded yet and web can not use Lua on Psych. They will be hardcoded soon, though. I've been a bit busy, so I haven't done it yet.

**Comment by loniop** [comment]
ok

**Comment by loniop** [comment]
> Sadly no as the stages are not hardcoded yet and web can not use Lua on Psych. They will be hardcoded soon, though. I've been a bit busy, so I haven't done it yet.

what would happen if all lua was removed?

**Comment by pahaze** [comment]
> > Sadly no as the stages are not hardcoded yet and web can not use Lua on Psych. They will be hardcoded soon, though. I've been a bit busy, so I haven't done it yet.
> 
> what would happen if all lua was removed?

It would play perfectly fine, hence why I want to move to hardcoded stages. But I'm busy with post surgery stuff, so I haven't had time to update the mod 🙃

**Comment by loniop** [comment]
ok thanks for explaining! I'm not experienced at all with mods, i just dig around already built mods stage and song files to change minor things. so i don't know how any fnf engine works completely. 
also thanks for the source! i was able to compile for linux so i can play.

**Comment by pahaze** [comment]
No problem! I plan to start updating on and off as I can, it just isn't easy yet. But I'll get there soon.
