### ISSUE TITLE
shotgun in Mist is broken

### ISSUE THREAD

**Issue by THESTORMZ** [pahaze/Mistful-Crimson-Morning#5]
### Describe your bug here.

when you are suppose to dodge the shotgun shot and fail it plays the hit animation but you do not die but continue instead.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by pahaze** [comment]
It isn't a bug. It was never meant to fully kill you, at least my coding of it wasn't (I made the script during development). It's only supposed to take some of your health, but let you continue with the song if you get hit.

**Comment by THESTORMZ** [comment]
i would have to take a second look, but I'm mostly sure it does not take any health. i don't fully remember.

**Comment by pahaze** [comment]
Checked on Linux and seems to be good there :man_shrugging: 

https://github.com/pahaze/Mistful-Crimson-Morning/assets/69173292/f6d46e1a-0b2a-49a6-9a6d-8bde4f1a18ef

**Comment by THESTORMZ** [comment]
ok i just have bad memory then XD
